const getters = {
    sidebar: state => state.app.sidebar,
    size: state => state.app.size,
    device: state => state.app.device,
    visitedViews: state => state.tagsView.visitedViews,
    cachedViews: state => state.tagsView.cachedViews,
    token: state => state.user.token,
    avatar: state => state.user.avatar,
    name: state => state.user.name,
    introduction: state => state.user.introduction,
    roles: state => state.user.roles,
    permission_routes: state => state.permission.routers,
    errorLogs: state => state.errorLog.logs,

    language: state => state.app.language,
    logininfo: state => state.user.logininfo,
    module: state => state.route.module,
    menuListInfo: state => state.route.menuListInfo,
    clientToken: state => state.user.clientToken,
    addRouters: state => state.permission.addRouters,
    menuIndex: state => state.route.menuIndex,
    asnycRoutes: state => state.permission.asnycRoutes,
    curFirstList: state => state.route.curFirstList,
}
export default getters